services:
  db:
    image: postgres
    ports:
      - '${POSTGRES_PORT}:5432'
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
  backend:
    image: node:22.18.0
    working_dir: /app
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - db
    command: >
      sh -e -c "
        npm ci &&
        npx wait-port db:5432 --timeout=30000 &&
        npm run typeorm -- migration:run -d src/data-source.ts &&
        npm run build &&
        npm run start:prod
      "
    ports:
      - '${BACKEND_PORT}:3000'

volumes:
  postgres_data:
